global:
  slack_api_url: '{{printf "%s" (env "SLACK_WEBHOOK")}}'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#aleksey_loktionov'
    text: 'Something wrong'
