{
 "title": "UI_Service_Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Env",
    "query": {
     "query": "label_values(kubernetes_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Http response time 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(ui_request_response_time_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to request",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_bucket{path=\"/\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP Requests with Error",
   "type": "timeseries",
   "description": "HTTP statuses 4xx and 5xx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UI HTTP Requests",
   "type": "timeseries",
   "description": "All HTTP requests that UI service receives",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"200\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}