apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "comment.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: gce-internal
  
spec:
  tls:
    - secretName: ui-ingress
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /{{ .Release.Name }}
        pathType: Prefix
        backend:
          service:
            name: {{ template "comment.fullname" . }}
            port:
              number: {{ .Values.service.externalPort }}
          
