version: '3'
services:

  fluentd:
    image: ${DOCKER_HUB_USERNAME}/fluentd:1.16-1
    container_name:  flu
    environment:
      - ELASTIC_PASSWORD=${FLUENT_PASS_TO_ELASTIC}
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - otus_back_net

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: ela
    expose:
      - 9200
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    networks:
      - otus_back_net

  kibana:
    image: ${DOCKER_HUB_USERNAME}/kibana:8.6.2
    ports:
      - "5601:5601"
    networks:
      - otus_back_net


networks:
  otus_back_net:
    external: true
