---
apiVersion: v1
kind: Service
metadata:
  name: post-{{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: reddit
    component: mongo
    post-db: "true"
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: reddit
    component: mongo
    post-db: "true"
    release: {{ .Release.Name }}
