comment:
  image:
    repository: fallgeratoor/comment
    tag: "1.0"
  service:
    externalPort: 9292

post:
  image:
    repository: fallgeratoor/post
    tag: prometheus
  service:
    externalPort: 5000

ui:
  image:
    repository: fallgeratoor/ui
    tag: "1.0"
  service:
    externalPort: 9292
