prometheus-pushgateway:
  ## If false, pushgateway will not be installed
  enabled: false

alertmanager:
  enabled: false


kube-state-metrics:
  enabled: false

server:
  global:
      scrape_interval: 30s
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [reddit-prometheus]




