prometheus-pushgateway:
  ## If false, pushgateway will not be installed
  enabled: false

alertmanager:
  enabled: false

prometheus-node-exporter:

  enabled: true

kube-state-metrics:
  enabled: true

server:
  global:
      scrape_interval: 30s
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: [reddit-prometheus]




