---
- name: Show info about the env this host belongs to
  ansible.builtin.debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Install docker-compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 755
